
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend/core
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/mydb?schema=public
      BACKEND_PORT: 3000
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FRONTEND_ORIGINS: http://localhost:5173  
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      VITE_BACKEND_URL: http://localhost:3000 
    ports:
      - "5173:3000"  
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge